### PR TITLE
Add missing Lab tests

### PR DESCRIPTION
**Pull request by tendomart**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket/issue number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests. If there is no automated tests, I tested this PR on my localhost.
- [ ] I included a screenshot or video of the change. This will help a lot the reviewers to test your changes and accelerate the approval.

### CODE REVIEW

**Comment by michaelbontyes** [comment]
Hello @tendomart, can you add a video that shows your tests of the lab tests added on your local so that the QA contributors know what to review, other contributors can learn from your experience working on the lab configuration, and it showcases your contribution which will be shown in the ✅ **Achievements** of the challenge as well? Thanks

**Comment by tendomart** [comment]
Ooh okk. I will see how to rectify those how dowe in the meantime translate French or include it without UTC encoding?

**Comment by michaelbontyes** [comment]
It is ok to take the time to correct them. Can you also share a video or screenshots of the lab test imported on your localhost for the QA? Thanks

**Comment by tendomart** [comment]
Alright will do so.

**Comment by tendomart** [comment]
Alright thanks for the Review. Am going to look into this again, I think the issue was caused by the editor which i used. Iam going to re-do this from scratch

**Comment by tendomart** [comment]
@michaelbontyes am moving this PR to  https://github.com/MadiroGlobalHealth/UVL-EMR/pull/44

**Pull request closed without merging**
