### PR TITLE
New drugs from UVL EMR Requirements: Add missing drugs

### PR DESCRIPTION
**Pull request by dancinoman**
I added drugs in distro level folder. ON the video, I show a test that the new drugs are available.

https://github.com/user-attachments/assets/4fb98bd9-5a08-4ada-8684-bb9ff64be72f

### CODE REVIEW

**Comment by michaelbontyes** [comment]
Hi @dancinoman , during QA I noticed that drugs were missing and not imported in OpenMRS despite being in Initializer config files. Here are a few:
Screenshot 2024-09-30 at 4 14 28 PM

Did you encounter the same issue on your local?

**Comment by dancinoman** [comment]
image
I found what was the issue! The drugs were missing because it had the same name even if the Uuid was different. But to fix this problem of drug disappearing(and there is many). What do you think that I rename those name to be unique with their doses?
Ex: ''Seringue A U U 5ML''
Instead of 1,2,3

**Comment by dancinoman** [comment]
Ok we are 2 good news and 1 tutorial video later
Good news: Those missing drugs are no longer missing and the dosage form concept was linked to the drugs.
Here is a tutorial on how I did.

https://github.com/user-attachments/assets/8dc4d6f6-b350-4372-bb8b-0cf9b96fc715

**Comment by dancinoman** [comment]
Just in case are you able to get Ac Fenac drug? I dont know why for me it is missing. It might be just me

**Comment by michaelbontyes** [comment]
@dancinoman , yes in the drugs. 
Screenshot 2024-10-01 at 5 19 39 PM

**Comment by dancinoman** [comment]
Altough, I see that you miss the dosage form. Did you have the new "drug_dosage_form_concepts.csv" file?

**Comment by michaelbontyes** [comment]
Yes, I see them now 👍

**Pull request merged**
