### PR TITLE
UVL-1: Add UVL to Docker volumes and Containers

### PR DESCRIPTION
**Pull request by sherrif10**
Ticket Number https://github.com/MadiroGlobalHealth/UVL-EMR/issues/8

Hey @michaelbontyes  , @pirupius  @jnsereko  . Any idea here, After testing these changes locally, the containers are still having the same names, unless i manually change them in the docker files ? Let me know your suggestions thanks.

### CODE REVIEW

**Comment by jnsereko** [comment]
hey @sherrif10, have you tried renaming the docker network?  You might need to edit the docker compose files and rework the start scripts.

Also this architecture supports inheritance of configuration (including build scripts) hence adding these configs at distro level should be enough.

**Comment by michaelbontyes** [comment]
@sherrif10 , I tested the PR locally but it doesn't change the names.

**Comment by sherrif10** [comment]
Hello @michaelbontyes  @jnsereko  for some reason , am blocked , unfortunately my changes reflect locally , Is there any where i can bench mark on ?

**Comment by jnsereko** [comment]
hey @sherrif10 you need to change the project name in we supply to docker compose.  Add the code below on [distro/pom.xml at line 192](https://github.com/MadiroGlobalHealth/UVL-EMR/blob/main/distro/pom.xml#L192)
```
<execution>
  <id>Rename project name to UVL</id>
  <phase>process-resources</phase>
  <goals>
    <goal>run</goal>
  </goals>
  <configuration>
    <target>
      <echo message="Rename project name to UVL in ozone scripts" />
      <replace
        dir="${project.build.directory}/${project.artifactId}-${project.version}/run/docker/scripts"
        includes="*.sh"
        token='-p ozone'
        value='-p uvl'/>
    </target>
  </configuration>
</execution>
```

**Comment by sherrif10** [comment]
Closing this for now

**Pull request closed without merging**
