### PR TITLE
Add the Data Visualizer module from UgandaEMR

### PR DESCRIPTION
**Pull request by dancinoman**
Added the module as the install name module is displayed here: 
https://www.npmjs.com/package/@ugandaemr/esm-data-visualizer-app
`@ugandaemr/esm-data-visualizer-app`
image

Then the data visualizer should appear on the front-end right after that like on the image below.
image

### CODE REVIEW

**Comment by WodPachua** [comment]
Thanks @dancinoman Do you have a video where this is appearing in your local host successfully?

**Comment by michaelbontyes** [comment]
Thank you @dancinoman! 🙌

**Comment by dancinoman** [comment]
@WodPachua 
https://github.com/user-attachments/assets/e36bef19-621b-4000-9b6f-e52c6421fd94

**Comment by WodPachua** [comment]
Awesome 💙 @dancinoman

**Pull request merged**
