### PR TITLE
Test adding billable lab services via liquibase

### PR DESCRIPTION
**Pull request by WodPachua**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket/issue number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests. If there is no automated tests, I tested this PR on my localhost.
- [x] I included a screenshot or video of the change. This will help a lot the reviewers to test your changes and accelerate the approval. 

## Summary
- Added Service Types
- Added Payment Types
- Added procedures
- Added billable services for Lab Tests, Procedures, Drugs
- Added Prices for all Billable Services (Lab tests, Procedures, Drugs)
- Fixed issue with billing-check-in form showing in home screen

## Screenshots or video
- Added billable services along with prices
billable-services-loading

- Fixed issue with billing-check-in form showing in home screen
bill-form-fix

## Related Issue
[Add billable services in billing using Liquibase domain with Initializer](https://github.com/MadiroGlobalHealth/UVL-EMR/issues/36)

### CODE REVIEW

**Comment by michaelbontyes** [comment]
@WodPachua Can you add a video or screenshots of the billable services and their costs added? Thanks

**Comment by WodPachua** [comment]
Hello @michaelbontyes 

I am getting this error after making these changes... any idea why I cant retrieve the billable services, yet have confirmed they are present in the database
image

**Comment by michaelbontyes** [comment]
I'd suggest you to coordinate with @caitlinmac who's also involved on configuring the services, as well as Jonathan and the squad as needed.

**Comment by michaelbontyes** [comment]
I know @caitlinmac was working on adding the billing concepts in configs so it might be related.

**Comment by WodPachua** [comment]
Alright... Sure will do.

**Comment by michaelbontyes** [comment]
@WodPachua , looking into the PR, it seems that some of your SQL scripts might conflict with existing Payement Services and Methods already added through other configurations. I can come back to it tomorrow if needed.

**Comment by WodPachua** [comment]
Oh I see... I actually have removed all the previous configurations added, except the service types which I couldn't find a related table for them for some reason in the database.

**Comment by WodPachua** [comment]
Let me ping her, and see if I can catch her tonight...

**Comment by WodPachua** [comment]
> Regarding the list of payement methods, I've wanted to revisit the list so we can have:
> - Insured cost
> - Non-insured cost
> - Cash
> - Mobile money
> 
> This way "Insured cost and non-insured cost" can be used to upon configuration to populate the 2 prices of each billable services and "Cash and Mobile money" can be used upon payement of the bills at the cashier.
> 
> What do you think?

Let me try to implement this, now that we have a way to load prices successfully as in the video attached @michaelbontyes

**Comment by WodPachua** [comment]
Hlo @michaelbontyes does this reflect your proposal?
bill-pay

**Comment by michaelbontyes** [comment]
Yes, exactly!

**Comment by michaelbontyes** [comment]
@WodPachua , how is it going with the billable services and prices?

**Comment by WodPachua** [comment]
I was waiting on the concepts to be added from the other tickets, but now have a good ahead, so am back to work on it

**Comment by WodPachua** [comment]
@michaelbontyes I have add all the prices. I have also updated the [PR Summary](https://github.com/MadiroGlobalHealth/UVL-EMR/pull/42#issue-2562957477) above with the tasks/changes made.

**Pull request merged**
