### PR TITLE
Missing lab tests

### PR DESCRIPTION
**Pull request by tendomart**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket/issue number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests. If there is no automated tests, I tested this PR on my localhost.
- [ ] I included a screenshot or video of the change. This will help a lot the reviewers to test your changes and accelerate the approval.

### CODE REVIEW

**Comment by tendomart** [comment]
@michaelbontyes  I now have two concepts  (Urea and Ecography) showing up and 7 others not showing,

am not sure what the cause even after rebuilding the search index, could it be the mode in which they where registered as members in the convset ?file:///home/tendo/Videos/Screencasts/concepts.mp4

**Comment by michaelbontyes** [comment]
@tendomart , isn't because you don't have UUID in the CSV? Here is a link if you want to generate them: https://www.uuidgenerator.net/version4

Screenshot 2024-10-08 at 5 32 12 PM

**Comment by tendomart** [comment]
Yes I had them initially in the previous commit and non of them was showing..

**Comment by tendomart** [comment]
But am gonna add them back and we see what happens

**Comment by tendomart** [comment]
@michaelbontyes  this clip shows adding what happens after adding UUID's

[madiro.webm](https://github.com/user-attachments/assets/34456cbe-62a7-4a64-bc00-7230ac8d5bee)

**Comment by tendomart** [comment]
Screenshot from 2024-10-09 01-58-47

**Comment by michaelbontyes** [comment]
@tendomart the dataclass and datatype used in requirements seem incorrect. I updated them with value allowed by OpenMRS (`test` for `dataclass` and `Numeric`/`Text` for `datatype`) so that you can test again.
Screenshot 2024-10-10 at 9 45 15 AM

**Comment by tendomart** [comment]
@michaelbontyes  I think the issue is now resolved, you can take a look at the clip after testing all the missing concepts.

[Uploading complete_concepts.webm…]()

**Comment by tendomart** [comment]
Yes  @michealbonteys, I actually did changes to reflect the updates you
did..and there was no failure I also removed Ecography because it was
ambiguous with ultrasound..So it all works well according to the clip.
Unless there's a new change I still need to add

**Comment by michaelbontyes** [comment]
Thank you @tendomart 🙏🏻

**Pull request merged**
